// Impressum und Datenschutz für die MARKETING-SEITE.
//
// ⚠️ Diese Texte gelten NUR für synapsio.solutions, nicht für die App unter app.synapsio.solutions.
// Die App verarbeitet Kundendaten und braucht ihre eigene, ausführlichere Erklärung.
//
// ⚠️ WARUM ES DIESE SEITEN ÜBERHAUPT GIBT. Vorher lagen Impressum, Datenschutz und AGB nur als PDF
// im /public-Ordner. Beide waren inhaltlich überholt: das Impressum wies Jakob Ibrahim als
// natürliche Person aus, obwohl seit dem 03.07.2026 die Synapsio UG Anbieterin ist, und die
// Datenschutzerklärung war ein Template, das auf jeder Seite sichtbar "Generated by LegalKit —
// consult an attorney" trug. Ausserdem verlangt § 5 DDG "unmittelbar erreichbar", was bei einem
// PDF verbreitet bezweifelt wird. Die PDFs bleiben liegen, sind aber nicht mehr verlinkt.
//
// ⚠️ KEINE RECHTSBERATUNG. Vor dem ersten Pilotkunden anwaltlich prüfen lassen. Offen ist
// insbesondere die USt-IdNr. (unten auskommentiert, sobald sie vorliegt eintragen).

export const COMPANY = {
  name: "Synapsio UG (haftungsbeschränkt)",
  street: "Berliner Allee 87 a",
  city: "14621 Schönwalde-Glien",
  country: "Deutschland",
  countryEn: "Germany",
  register: "HRB 42364 P",
  court: "Amtsgericht Potsdam",
  courtEn: "Local Court of Potsdam",
  directors: "Jakob Ibrahim, Luis Marten Boy",
  email: "contact@synapsio.co.site",
};

export const legalCopy = {
  de: {
    imprint: {
      title: "Impressum",
      lede: "Angaben gemäß § 5 Digitale-Dienste-Gesetz (DDG).",
      blocks: [
        { h: "Anbieterin", p: [
          COMPANY.name,
          `${COMPANY.street}, ${COMPANY.city}`,
          COMPANY.country,
        ] },
        { h: "Handelsregister", p: [
          `Eingetragen im Handelsregister des ${COMPANY.court}`,
          `Registernummer: ${COMPANY.register}`,
        ] },
        { h: "Vertretungsberechtigte Geschäftsführer", p: [COMPANY.directors] },
        { h: "Kontakt", p: [`E-Mail: ${COMPANY.email}`] },
        { h: "Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV", p: [
          "Jakob Ibrahim, Anschrift wie oben.",
        ] },
        { h: "Verbraucherstreitbeilegung", p: [
          "Wir sind nicht bereit und nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.",
        ] },
        { h: "Haftung für Inhalte und Links", p: [
          "Die Inhalte dieser Seiten wurden mit Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität können wir keine Gewähr übernehmen.",
          "Diese Seite enthält Links zu externen Websites Dritter. Auf deren Inhalte haben wir keinen Einfluss; für sie ist der jeweilige Anbieter verantwortlich.",
        ] },
      ],
    },
    privacy: {
      title: "Datenschutzerklärung",
      lede: "Diese Erklärung gilt für die Website synapsio.solutions. Für die Anwendung unter app.synapsio.solutions gelten gesonderte Bedingungen, die Sie dort erhalten.",
      blocks: [
        { h: "Verantwortliche Stelle", p: [
          `${COMPANY.name}, ${COMPANY.street}, ${COMPANY.city}`,
          `Vertreten durch: ${COMPANY.directors}`,
          `E-Mail: ${COMPANY.email}`,
        ] },
        { h: "Keine Cookies, keine Analyse, keine externen Inhalte", p: [
          "Diese Website setzt keine Cookies, bindet keine Analyse- oder Trackingdienste ein und lädt keine Inhalte von fremden Servern. Schriftarten und alle übrigen Dateien liefern wir selbst aus. Es gibt deshalb kein Einwilligungsbanner, weil es nichts einzuwilligen gibt.",
        ] },
        { h: "Hosting und Server-Logdateien", p: [
          "Die Website wird über GitHub Pages bereitgestellt, einen Dienst der GitHub, Inc., 88 Colin P Kelly Jr Street, San Francisco, CA 94107, USA.",
          "Beim Abruf der Seiten verarbeitet der Hoster technisch notwendige Zugriffsdaten, insbesondere Ihre IP-Adresse, Datum und Uhrzeit des Abrufs, die abgerufene Datei sowie Angaben zu Browser und Betriebssystem. Diese Verarbeitung ist erforderlich, um die Seite auszuliefern und ihren Betrieb abzusichern.",
          "Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in der zuverlässigen und sicheren Bereitstellung der Website. Die Übermittlung in die USA stützt sich auf die Zertifizierung des Anbieters unter dem EU-US Data Privacy Framework beziehungsweise auf Standardvertragsklauseln.",
        ] },
        { h: "Kontaktaufnahme", p: [
          "Wenn Sie uns per E-Mail schreiben, verarbeiten wir Ihre Angaben ausschließlich, um Ihre Anfrage zu beantworten. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO bei vertragsbezogenen Anfragen, sonst Art. 6 Abs. 1 lit. f DSGVO. Wir löschen die Daten, sobald sie nicht mehr erforderlich sind und keine gesetzlichen Aufbewahrungsfristen entgegenstehen.",
        ] },
        { h: "Terminvereinbarung", p: [
          "Für Gesprächstermine verlinken wir auf den Dienst Cal.com. Erst wenn Sie diesen Link öffnen, verlassen Sie unsere Website; ab diesem Zeitpunkt gilt die Datenschutzerklärung des Anbieters. Von unserer Seite werden dabei keine Daten übertragen.",
        ] },
        { h: "Ihre Rechte", p: [
          "Sie haben das Recht auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung der Verarbeitung (Art. 18), Datenübertragbarkeit (Art. 20) sowie das Recht, einer Verarbeitung auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO zu widersprechen (Art. 21). Eine Nachricht an die oben genannte Adresse genügt.",
        ] },
        { h: "Beschwerderecht", p: [
          "Sie können sich bei einer Datenschutz-Aufsichtsbehörde beschweren. Für uns zuständig ist: Die Landesbeauftragte für den Datenschutz und für das Recht auf Akteneinsicht Brandenburg, Stahnsdorfer Damm 77, 14532 Kleinmachnow.",
        ] },
        { h: "Stand", p: [
          "Diese Erklärung gilt ab August 2026. Wir passen sie an, wenn sich die Verarbeitung ändert.",
        ] },
      ],
    },
  },
  en: {
    imprint: {
      title: "Legal Notice",
      lede: "Information pursuant to § 5 of the German Digital Services Act (DDG).",
      blocks: [
        { h: "Provider", p: [
          COMPANY.name,
          `${COMPANY.street}, ${COMPANY.city}`,
          COMPANY.countryEn,
        ] },
        { h: "Commercial register", p: [
          `Registered with the ${COMPANY.courtEn}`,
          `Registration number: ${COMPANY.register}`,
        ] },
        { h: "Managing directors", p: [COMPANY.directors] },
        { h: "Contact", p: [`Email: ${COMPANY.email}`] },
        { h: "Responsible for content under § 18 (2) MStV", p: [
          "Jakob Ibrahim, address as above.",
        ] },
        { h: "Consumer dispute resolution", p: [
          "We are neither willing nor obliged to take part in dispute resolution proceedings before a consumer arbitration board.",
        ] },
        { h: "Liability for content and links", p: [
          "These pages were prepared with care. We cannot guarantee that the information is accurate, complete or current.",
          "This site links to external websites. We have no influence over their content; the respective provider is responsible for it.",
        ] },
      ],
    },
    privacy: {
      title: "Privacy Policy",
      lede: "This policy covers the website synapsio.solutions. The application at app.synapsio.solutions is governed by separate terms provided there.",
      blocks: [
        { h: "Controller", p: [
          `${COMPANY.name}, ${COMPANY.street}, ${COMPANY.city}, ${COMPANY.countryEn}`,
          `Represented by: ${COMPANY.directors}`,
          `Email: ${COMPANY.email}`,
        ] },
        { h: "No cookies, no analytics, no third-party content", p: [
          "This website sets no cookies, embeds no analytics or tracking services, and loads nothing from third-party servers. Fonts and all other assets are served by us. There is therefore no consent banner, because there is nothing to consent to.",
        ] },
        { h: "Hosting and server logs", p: [
          "The site is served through GitHub Pages, a service of GitHub, Inc., 88 Colin P Kelly Jr Street, San Francisco, CA 94107, USA.",
          "When you open a page, the host processes technically necessary access data, in particular your IP address, the date and time, the file requested, and details of your browser and operating system. This is required to deliver the page and keep it secure.",
          "The legal basis is Art. 6(1)(f) GDPR; our legitimate interest is the reliable and secure operation of the website. The transfer to the USA is based on the provider's certification under the EU-US Data Privacy Framework or on standard contractual clauses.",
        ] },
        { h: "Contacting us", p: [
          "If you email us, we process your details solely to answer your enquiry. The legal basis is Art. 6(1)(b) GDPR for contract-related enquiries and otherwise Art. 6(1)(f) GDPR. We delete the data once it is no longer needed and no statutory retention period applies.",
        ] },
        { h: "Booking a call", p: [
          "For scheduling we link to the service Cal.com. You leave our website only when you open that link; from that point the provider's privacy policy applies. No data is transmitted from our side.",
        ] },
        { h: "Your rights", p: [
          "You have the right of access (Art. 15 GDPR), rectification (Art. 16), erasure (Art. 17), restriction of processing (Art. 18), data portability (Art. 20), and the right to object to processing based on Art. 6(1)(f) GDPR (Art. 21). A message to the address above is enough.",
        ] },
        { h: "Right to complain", p: [
          "You may lodge a complaint with a data protection supervisory authority. Ours is: Die Landesbeauftragte für den Datenschutz und für das Recht auf Akteneinsicht Brandenburg, Stahnsdorfer Damm 77, 14532 Kleinmachnow, Germany.",
        ] },
        { h: "Status", p: [
          "This policy applies from August 2026. We update it when our processing changes.",
        ] },
      ],
    },
  },
} as const;
